### ISSUE TITLE
promise, child_process: nextTick callback not invoked

### ISSUE THREAD

**Issue by lolBig** [yodaos-project/ShadowNode#217]
```js
// test-child.js
console.log('start');

Promise.resolve().then(() => {
  process.nextTick(() => console.log('tick'));
});

// test-parent.js
var child_process = require('child_process');
child_process.fork('./test-child.js');
```

print `start` but no `tick`

**Comment by yorkie** [comment]
This should be flagged with `Promise`.

**Comment by legendecas** [comment]
Looks like this issue has been fixed in the latest Promise fixes.

Either run test case directly or fork it through `child_process.fork`.

**Comment by yorkie** [comment]
@legendecas Do we have already test case to ensure?

**Comment by yorkie** [comment]
> Looks like this issue has been fixed in the latest Promise fixes.
> 
> Either run test case directly or fork it through `child_process.fork`.

Works for my local machine, too.
