### ISSUE TITLE
The _write() method of the fs module WriteStream is not called _onwrite()

### ISSUE THREAD

**Issue by caihongyun** [yodaos-project/ShadowNode#248]
https://github.com/Rokid/ShadowNode/blob/4d9484424de7e2d3b11663c3d71d126f97d2722b/src/js/fs.js#L843

example: 
###  
    var fs = require('fs');
    var ws = fs.createWriteStream('a.txt');
    ws.write('1');
    ws.write('2');
The above code cannot write '2' to a.txt.

reference：
https://github.com/Rokid/ShadowNode/blob/4d9484424de7e2d3b11663c3d71d126f97d2722b/src/js/net.js#L187

**Comment by yorkie** [comment]
This should be fixed by #566 :)
