### ISSUE TITLE
ShadowDebugger: wrap the IoT.js Code with electron

### ISSUE THREAD

**Issue by yorkie** [yodaos-project/ShadowNode#32]
Use Electron to wrap https://samsung.github.io/iotjscode/ to release the first version of debugger :)

**Comment by legendecas** [comment]
What about adapting [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) so that existing debug tools like Chrome Inspector, IDEs(Webstorm, VSCode debugger) can be used in development

**Comment by yorkie** [comment]
A Lua Debugger based on Chrome DevTools: https://github.com/muzuiget/mare

**Comment by algebrait** [comment]
Memory analyze tool is very important to ShadoeNode. I will study if jerry can support V8 heapsnapshot

**Comment by yorkie** [comment]
The v0.8.0 has been released today, let's re-schedule this feature in our next version :)

**Comment by yorkie** [comment]
Just closing this because we have decided not creating any **new** IDE or editors, and just integrating the current development tools.
