### ISSUE TITLE
jerry: vm assertion failure on class statement

### ISSUE THREAD

**Issue by legendecas** [yodaos-project/ShadowNode#467]
* **Version**: 0.11.1
* **Platform**: *
* **Subsystem**: jerry

```js
module.exports = class Foo {}
```

```
ICE: Assertion 'frame_ctx_p->registers_p + register_end + frame_ctx_p->context_depth == stack_top_p' failed at /Users/lucas/Developer/github/ShadowNode/deps/jerry/jerry-core/vm/vm.c(vm_loop):1256.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

Possible related https://github.com/Rokid/ShadowNode/pull/450

**Comment by yorkie** [comment]
Could this be reproduced on JerryScript?

**Comment by legendecas** [comment]
Seems working on jerry master branch.

**Comment by yorkie** [comment]
@fighterkin do you mind have a look?

**Comment by yorkie** [comment]
@legendecas I could not reproduce this bug at `master`, does this get fixed?

**Comment by legendecas** [comment]
Doesn't seem reproducible, closing for now.
