### ISSUE TITLE
stream: use data struct of node stream in shadownode stream module

### ISSUE THREAD

**Issue by Txiaozhe** [yodaos-project/ShadowNode#495]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

When I optimize the stream module of shadownode, I found its data struct is difference from node stream module, it's not very appropriate to implement some features, so I propose to change it!

**Comment by Txiaozhe** [comment]
just like:
```json
{
    "head":{
        "data":"a",
        "next":{
            "data":"b",
            "next":{
                "data":"c",
                "next":null
            }
        }
    },
    "tail":{
        "data":"c",
        "next":null
    },
    "length":3
}
```

every node in this linked list is one element of stream data.

**Comment by yorkie** [comment]
Could you please point out where does the structure store?

**Comment by Txiaozhe** [comment]
> Could you please point out where does the structure store?

You mean the struct implementation file? In node project: 
node/lib/internal/streams/buffer_list.js
Or you mean where the stream data store?

**Comment by yorkie** [comment]
I'm still unsure what's the detailed cases, could you please give some problem?

**Comment by Txiaozhe** [comment]
Yes, when I optimize the stream module for issue #185, I need to add one 'objectMode' option for stream api, but in node, when the 'objectMode' is true, the data of stream will be read one-by-one when I invoke the 'read' method of stream object.
But in ShadowNode, the data struct of stream is array, it is not fast for read one-by-one but 
linked list is faster. And I hope ShadowNode will close to Node in every aspect.
This is my point of view, thanks:)

**Comment by Txiaozhe** [comment]
In stream module of Node, when the 'objectMode' option is true, 'read' operation will execute:
* read the first one element of stream
* delete the element after read
* all element move forward one step
it more suitable for linked list.

**Comment by yorkie** [comment]
> ShadowNode will close to Node in every aspect.

Partially agreed with you, the problem to ShadowNode is not same like Node.js, we have to think about the memory more, so what you wanna add the `objectMode` to the stream? What's the scenario of objectMode in edge device?

**Comment by Txiaozhe** [comment]
I am sorry I am optimizing the stream module for issue: #185, but I haven't thought of any exact scenarios that can be applied to this option yet.

**Comment by yorkie** [comment]
Closing this because of moving discussion to #185.
