### ISSUE TITLE
parent can not get the message from the child when child forked with execPath of different iotjs version.

### ISSUE THREAD

**Issue by littleGauze** [yodaos-project/ShadowNode#499]
* **Version**: v0.10.10, v0.11.0
* **Platform**: Linux buildroot 4.9.54 #1 SMP PREEMPT Wed Oct 24 14:20:32 HKT 2018 aarch64 GNU/Linux
* **Subsystem**:

This bug comes up when I use child_process.fork method with a different version of iotjs executable.
I run the parent.js with v0.10.10 and fork child with v0.11.0.

here is my code:

*parent.js*
```js
var path = require('path')
var cp = require('child_process')
var execPath = path.resolve(__dirname, './iotjs')
var child = cp.fork(path.resolve(__dirname, './child.js'), {
  stdio: 'inherit',
  execPath: execPath
})

child.on('message', msg => {
  console.log('__parent got message___ ', msg)
})

setInterval(() => {}, 1000)
```
*child.js*
```js
process.title = 'child'
console.log('child started')
setTimeout(() => {
  console.log('process.send method ', process.send)
  process.send('this message send from child')
}, 2000)
```

then I got this message:
```shell
# iotjs parent.js
child started
process.send method  function(){/* ecmascript */}

```
the `message` event will never be called.

**Comment by legendecas** [comment]
cb68b86 - child_process: introduce binary protocol to optimizing performance (#393) introduced a new messaging protocol between the parent process and the children. 

Should we assure cross version compatibility on this?

/cc @lolBig

**Comment by legendecas** [comment]
As discussed with @lolBig and @yorkie, the compatibility on cross version IPC would not be assured in ShadowNode. Yet, we'd make our best efforts to keep cross version IPC compatible and efficient.
