### ISSUE TITLE
arm 版本静态链接

### ISSUE THREAD

**Issue by tqcenglish** [yodaos-project/ShadowNode#539]
交叉编译失败后在 pi 上编译成功，编译参数
```
./tools/build.py --target-arch=arm --target-os=linux  --buildtype=release  --target-board=rpi2  --static
```
在其他环境运行提示缺少 libdbus-1.so.3
是否有参数设置静态连接的方式，将 libdbus-1.so.3 也包含在 iot.js

**Comment by yorkie** [comment]
可以参考这里 https://github.com/yodaos-project/ShadowNode/blob/master/tools/build.py#L99-L100

**Comment by yorkie** [comment]
duplicated with https://github.com/yodaos-project/ShadowNode/issues/530.
