### ISSUE TITLE
switch jerryscript to quickjs

### ISSUE THREAD

**Issue by luanwulin** [yodaos-project/ShadowNode#549]
will shadownode consider switch jerry to quickjs?
![image](https://user-images.githubusercontent.com/16553854/61941875-e878db80-afca-11e9-94ef-ab0ca3a75da8.png)

**Comment by yorkie** [comment]
We implemented the N-API which depends on JerryScript heavily, and it seems quickjs takes more resources than JerryScript, so the JerryScript is still the best VM fits the target of ShadowNode :)

**Comment by luanwulin** [comment]
@yorkie all right.thx
