### ISSUE TITLE
could not listen SIGCHLD on JS land

### ISSUE THREAD

**Issue by legendecas** [yodaos-project/ShadowNode#560]
* **Version**: v0.11.x
* **Platform**: darwin
* **Subsystem**: process

SIGCHLD would not be installed on new listeners.
```js
process.on('SIGCHLD', (signal) => { console.log(signal) })
```

Also SIGCHLD( and others like SIGUSR1 etc.) has different values on linux/darwin, only linux version was supported currently.

Refs: http://man7.org/linux/man-pages/man7/signal.7.html

**Comment by yorkie** [comment]
Removed the "good first issue" label just like #558.
