### ISSUE TITLE
What is the reason for removing dbus native support in shadownode in plan?

### ISSUE THREAD

**Issue by Txiaozhe** [yodaos-project/ShadowNode#571]

**Comment by yorkie** [comment]
Because the D-Bus is not at the official module list.

**Comment by Txiaozhe** [comment]
> Because the D-Bus is not at the official module list.

The official of 'official module' is Node or ShadowNode?

**Comment by yorkie** [comment]
What I did mean is "Node.js" official core modules :)

**Comment by Txiaozhe** [comment]
> What I did mean is "Node.js" official core modules :)

Oh  ???  but neither mqtt

**Comment by Txiaozhe** [comment]
> What I did mean is "Node.js" official core modules :)

Oh  ???  but neither mqtt

**Comment by yorkie** [comment]
Yes, so the mqtt.js is also in this plan.

**Comment by Txiaozhe** [comment]
> Yes, so the mqtt.js is also in this plan.
It is so regret :(
